<!DOCTYPE html><html lang="zh-cn"><head><meta charset="utf-8"><meta name="X-UA-Compatible" content="IE=edge"><title> 讨论下 RxJava 里的 onError · IM XIE</title><meta name="description" content="讨论下 RxJava 里的 onError - 谢三弟"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="short icon" href="/images/favicon.ico"><link rel="stylesheet" href="/css/apollo.css"><link rel="search" type="application/opensearchdescription+xml" href="http://imxie.cc/atom.xml" title="IM XIE"></head><body><div class="wrap"><header><a href="/" class="logo-link"><img src="/images/logo.png"></a><ul class="nav nav-list"><li class="nav-list-item"><a href="/" target="_self" class="nav-list-link">BLOG</a></li><li class="nav-list-item"><a href="/archives/" target="_self" class="nav-list-link">ARCHIVE</a></li><li class="nav-list-item"><a href="https://github.com/xcc3641" target="_blank" class="nav-list-link">GITHUB</a></li><li class="nav-list-item"><a href="/about/" target="_self" class="nav-list-link">ABOUT</a></li></ul></header><section class="container"><div class="post"><article class="post-block"><h1 class="post-title">讨论下 RxJava 里的 onError</h1><div class="post-info">2016年6月1日</div><div class="post-content"><p>因为上次在网络请求里用到了 <code>onErrorReturn</code> 所以想自己实践下和搞清楚 RxJava 里异常处理到底是怎么回事，以及自己如何更好的使用。</p>
<a id="more"></a>
<!-- toc -->
<h3 id="栗子"><a href="#栗子" class="headerlink" title="栗子"></a>栗子</h3><figure class="highlight java"><table><tr><td class="code"><pre><div class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">RxJavaTest</span> </span>&#123;</div><div class="line">    <span class="keyword">static</span> <span class="keyword">int</span>[] arrayA = <span class="keyword">new</span> <span class="keyword">int</span>[<span class="number">2</span>];</div><div class="line">    <span class="keyword">static</span> List&lt;Integer&gt; listB = <span class="keyword">new</span> ArrayList&lt;&gt;();</div><div class="line"></div><div class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</div><div class="line">        listB.add(<span class="number">1</span>);</div><div class="line">        listB.add(<span class="number">2</span>);</div><div class="line">        listB.add(<span class="number">3</span>);</div><div class="line">        errorTest();</div><div class="line">    &#125;</div><div class="line"></div><div class="line">    <span class="function"><span class="keyword">private</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">errorTest</span><span class="params">()</span> </span>&#123;</div><div class="line">        Observable.from(listB)</div><div class="line">            .doOnNext(integer -&gt; arrayA[integer] = integer)</div><div class="line">            .subscribe(integer -&gt; &#123;</div><div class="line">            &#125;, throwable -&gt; &#123;</div><div class="line">                System.out.println(<span class="string">"在onError处理了:"</span> + throwable.toString());</div><div class="line">            &#125;);</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>可以看到我在这里模拟了一个越界异常，在 <code>errorTest()</code> 方法里做写了遍历列表 <code>listB</code> 并且将值赋值给数组 <code>arrayA</code> 对应角标。</p>
<p>运行以上程序在控制台输出的是：</p>
<figure class="highlight plain"><table><tr><td class="code"><pre><div class="line">在onError处理了:java.lang.ArrayIndexOutOfBoundsException: 2</div></pre></td></tr></table></figure>
<p>现在我们做一点改变：</p>
<p><strong>在 <code>errorTest</code> 方法里加入 <code>onErrorReturn</code> 并且返回 null </strong></p>
<figure class="highlight java"><table><tr><td class="code"><pre><div class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">errorTest</span><span class="params">()</span> </span>&#123;</div><div class="line">    Observable.from(listB)</div><div class="line">        .doOnNext(integer -&gt; arrayA[integer] = integer)</div><div class="line">        .onErrorReturn(throwable -&gt; &#123;</div><div class="line">            System.out.println(<span class="string">"在onErrorReturn处理了:"</span> + throwable.toString());</div><div class="line">            <span class="keyword">return</span> <span class="keyword">null</span>;</div><div class="line">        &#125;)</div><div class="line">        .subscribe(integer -&gt; &#123;</div><div class="line"></div><div class="line">        &#125;, throwable -&gt; &#123;</div><div class="line">            System.out.println(<span class="string">"在onError处理了:"</span> + throwable.toString());</div><div class="line">        &#125;);</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>现在再运行程序得到在控制台的输出是：</p>
<figure class="highlight plain"><table><tr><td class="code"><pre><div class="line">在onErrorReturn处理了:java.lang.ArrayIndexOutOfBoundsException: 2</div></pre></td></tr></table></figure>
<p>发现异常只在 onErrorReturn 处理了，并没有在 onError 里。</p>
<p>难道只要写了 onErrorReturn 处理了异常就不会抛到 onError 里吗？</p>
<p>带着这个疑问，我们再修改下 errorTest() 方法：<br><figure class="highlight java"><table><tr><td class="code"><pre><div class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">errorTest</span><span class="params">()</span> </span>&#123;</div><div class="line">    Observable.from(listB)</div><div class="line">        .doOnNext(integer -&gt; arrayA[integer] = integer)</div><div class="line">        .onErrorReturn(throwable -&gt; &#123;</div><div class="line">            System.out.println(<span class="string">"在onErrorReturn处理了:"</span> + throwable.toString());</div><div class="line">            <span class="keyword">return</span> <span class="number">3</span>;</div><div class="line">        &#125;)</div><div class="line">        .doOnNext(integer -&gt; arrayA[integer] = integer)</div><div class="line">        .subscribe(integer -&gt; &#123;</div><div class="line">        &#125;, throwable -&gt; &#123;</div><div class="line">            System.out.println(<span class="string">"在onError处理了:"</span> + throwable.toString());</div><div class="line">        &#125;);</div><div class="line">&#125;</div></pre></td></tr></table></figure></p>
<p>让 onErrorReturn 处理了异常后并且返回一个 3，随后继续进行赋值操作。</p>
<p>现在运行程序，控制台输出：<br><figure class="highlight plain"><table><tr><td class="code"><pre><div class="line">在onErrorReturn处理了:java.lang.ArrayIndexOutOfBoundsException: 2</div><div class="line">在onError处理了:java.lang.ArrayIndexOutOfBoundsException: 3</div></pre></td></tr></table></figure></p>
<h3 id="总结"><a href="#总结" class="headerlink" title="总结"></a>总结</h3><p><strong>onErrorRetrun</strong> 能够捕获在它之前发生的异常，它之后流中的操作发生的异常就它就不会管了。<br>经过小栗子的演示，我们现在理解了 onErrorReturn 的作用域，从而明白该什么时候使用它。</p>
<p>参考文章：</p>
<ul>
<li><a href="https://mcxiaoke.gitbooks.io/rxdocs/content/operators/Catch.html" target="_blank" rel="external">https://mcxiaoke.gitbooks.io/rxdocs/content/operators/Catch.html</a></li>
<li><a href="https://dzone.com/articles/rxjavas-side-effect-methods" target="_blank" rel="external">https://dzone.com/articles/rxjavas-side-effect-methods</a></li>
<li><a href="http://blog.chengyunfeng.com/?p=976" target="_blank" rel="external">http://blog.chengyunfeng.com/?p=976</a></li>
</ul></div></article></div></section><footer><div class="paginator"></div><div data-thread-key="hide/tao-lun-Rx-onError.html" data-title="讨论下 RxJava 里的 onError" data-url="http://imxie.cc/hide/tao-lun-Rx-onError.html" data-author-key="1" class="ds-thread"></div><script>var duoshuoQuery = {short_name:"imxie"};
(function() {
    var ds = document.createElement('script');
    ds.type = 'text/javascript';ds.async = true;
    ds.src = 'http://www.imxie.cc/js/embed.js';
    ds.charset = 'UTF-8';
    (document.getElementsByTagName('head')[0] 
     || document.getElementsByTagName('body')[0]).appendChild(ds);
})();

</script><div class="copyright"><p>© 2014 - 2019 做一件值得的事.</p></div></footer></div><script async src="//cdn.bootcss.com/mathjax/2.6.1/MathJax.js?config=TeX-MML-AM_CHTML"></script><script>(function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;e=o.createElement(i);r=o.getElementsByTagName(i)[0];e.src='//www.google-analytics.com/analytics.js';r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));ga('create',"UA-80145821-1",'auto');ga('send','pageview');</script></body></html>